<?php
/**
 * @var \Riverstone\Quickview\Block\Product\View $block
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?=  /* @noEscape */ __('Qty') ?></span></label>
                    <div class="control">
                        <input
                            type="number"
                            name="qty"
                            id="qty"
                            maxlength="12"
                            value="<?=  /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                            title="<?=  /* @noEscape */ __('Qty') ?>" class="input-text qty"
                            data-validate="<?= $escaper->escapeHtml($block->jsonEncoderQuantityValidators()) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button
                    type="submit"
                    title="<?=  /* @noEscape */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                    <span><?=  /* @noEscape */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "riverstone_quickview/catalog_product": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
    {
        ".actions": {
            "Riverstone_Quickview/js/riverstone_tocart": {
            }
        }
    }
    </script>
<?php endif; ?>
